window.syn = {
  config: {
    clickChanges: true,
    clickSubmits: true,
    keypressSubmits: false,
    mouseupSubmits: false,
    radioClickChanges: true,
    focusChanges: false,
    linkHrefJS: false,
    keyCharacters: false,
    backspaceWorks: false,
    mouseDownUpClicks: false,
    tabKeyTabs: false,
    keypressOnAnchorClicks: false,
    optionClickBubbles: true,
    pointerEvents: true,
    touchEvents: false,
    ready: 2,
    clickChecks: true,
    changeChecks: false,
    changeBubbles: true,
    keysOnNotFocused: false,
    textareaCarriage: false,
    oninput: true,
    elementFromPage: true,
  },
}
